const products=[
{name:'Silk Sarees',category:'Sarees',price:3499,discount:'20% OFF',rating:4.9,image:'assets/images/silk-sarees.svg',arrival:true,best:true},
{name:'Cotton Sarees',category:'Sarees',price:1499,discount:'15% OFF',rating:4.7,image:'assets/images/cotton-sarees.svg',arrival:false,best:true},
{name:'Fancy Sarees',category:'Sarees',price:2599,discount:'25% OFF',rating:4.8,image:'assets/images/fancy-sarees.svg',arrival:true,best:false},
{name:"Women's Tops",category:'Tops',price:899,discount:'10% OFF',rating:4.6,image:'assets/images/womens-tops.svg',arrival:true,best:true},
{name:'Chudidar Sets',category:'Ethnic Sets',price:2199,discount:'18% OFF',rating:4.9,image:'assets/images/chudidar-sets.svg',arrival:false,best:true},
{name:'Kids Wear',category:'Kids',price:799,discount:'12% OFF',rating:4.5,image:'assets/images/kids-wear.svg',arrival:true,best:false},
{name:"Women's Innerwear",category:'Innerwear',price:599,discount:'8% OFF',rating:4.4,image:'assets/images/innerwear.svg',arrival:false,best:false}
];
const $=s=>document.querySelector(s);const grid=$('#productGrid'),bestGrid=$('#bestGrid'),slideTrack=$('#slideTrack'),toast=$('#toast');
let wishlist=JSON.parse(localStorage.getItem('thunarWishlist')||'[]');let cart=JSON.parse(localStorage.getItem('thunarCart')||'[]');let authMode='login';
function save(key,val){localStorage.setItem(key,JSON.stringify(val))}function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function productCard(p){const wished=wishlist.includes(p.name);return `<article class="product-card"><img src="${p.image}" alt="${p.name}"><div class="product-body"><div class="card-top"><span class="badge">${p.discount}</span><button class="wish ${wished?'active':''}" data-wish="${p.name}" aria-label="Wishlist ${p.name}">♥</button></div><h3>${p.name}</h3><p>${p.category} • ⭐ ${p.rating}</p><p class="price">₹${p.price.toLocaleString('en-IN')}</p><div class="card-actions"><button class="secondary-button" data-detail="${p.name}">View Details</button><button class="primary-button" data-cart="${p.name}">Add</button></div></div></article>`}
function renderProducts(){let items=[...products];const q=$('#searchInput').value.toLowerCase();const cat=$('#categoryFilter').value;const sort=$('#sortSelect').value;if(q)items=items.filter(p=>p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q));if(cat!=='all')items=items.filter(p=>p.category===cat);if(sort==='low-high')items.sort((a,b)=>a.price-b.price);if(sort==='high-low')items.sort((a,b)=>b.price-a.price);grid.innerHTML=items.map(productCard).join('')||'<p>No products found.</p>';bindCardButtons()}
function bindCardButtons(){document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(b.dataset.wish));document.querySelectorAll('[data-cart]').forEach(b=>b.onclick=()=>addCart(b.dataset.cart));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showToast(`${b.dataset.detail}: premium boutique selection now available.`))}
function toggleWish(name){wishlist=wishlist.includes(name)?wishlist.filter(x=>x!==name):[...wishlist,name];save('thunarWishlist',wishlist);renderProducts();showToast(wishlist.includes(name)?'Added to wishlist':'Removed from wishlist')}
function addCart(name){const item=products.find(p=>p.name===name);const found=cart.find(c=>c.name===name);found?found.qty++:cart.push({...item,qty:1});save('thunarCart',cart);renderCart();showToast('Added to cart')}
function renderCart(){const count=cart.reduce((s,i)=>s+i.qty,0);$('#cartCount').textContent=count;$('#cartItems').innerHTML=cart.map(i=>`<div class="cart-row"><span>${i.name}<br><small>₹${i.price} × ${i.qty}</small></span><button class="link-button" data-remove="${i.name}">Remove</button></div>`).join('')||'<p>Your cart is empty.</p>';$('#cartTotal').textContent=`Total: ₹${cart.reduce((s,i)=>s+i.price*i.qty,0).toLocaleString('en-IN')}`;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(i=>i.name!==b.dataset.remove);save('thunarCart',cart);renderCart()})}
function setup(){products.map(p=>p.category).filter((v,i,a)=>a.indexOf(v)===i).forEach(c=>$('#categoryFilter').insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));bestGrid.innerHTML=products.filter(p=>p.best).map(productCard).join('');slideTrack.innerHTML=products.filter(p=>p.arrival).map(p=>`<article class="slide"><div><p class="eyebrow">Fresh Drop</p><h3>${p.name}</h3><p>Soft colors, flattering finish, and boutique-ready elegance.</p><button class="primary-button" data-cart="${p.name}">Add to Cart</button></div><img src="${p.image}" alt="${p.name}"></article>`).join('');renderProducts();renderCart();bindCardButtons();updateUser()}
function openAuth(mode='login'){authMode=mode;$('#authTitle').textContent=mode==='login'?'Login':'Sign Up';$('#nameField').style.display=mode==='signup'?'block':'none';$('#switchAuth').textContent=mode==='login'?'Need an account? Sign up':'Already have an account? Login';$('#authModal').classList.add('open')}
function updateUser(){const user=JSON.parse(localStorage.getItem('thunarCurrentUser')||'null');$('#profileMenu').classList.toggle('active',!!user);$('#profileButton').textContent=user?`Hi, ${user.name.split(' ')[0]}`:'Guest';$('#loginNav').style.display=user?'none':'inline'}
$('#authForm').onsubmit=e=>{e.preventDefault();const name=$('#nameField').value.trim();const email=$('#emailField').value.trim();const password=$('#passwordField').value;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<6){showToast('Use a valid email and 6+ character password');return}let users=JSON.parse(localStorage.getItem('thunarUsers')||'[]');if(authMode==='signup'){if(!name){showToast('Please enter your name');return}if(users.some(u=>u.email===email)){showToast('Account already exists');return}users.push({name,email,password});save('thunarUsers',users)}const user=users.find(u=>u.email===email&&u.password===password);if(!user){showToast('Invalid login details');return}localStorage.setItem('thunarCurrentUser',JSON.stringify({name:user.name,email:user.email,remember:$('#rememberField').checked}));$('#authModal').classList.remove('open');updateUser();showToast(`Welcome ${user.name}`)};
$('#switchAuth').onclick=()=>openAuth(authMode==='login'?'signup':'login');$('#loginNav').onclick=()=>openAuth('login');$('#closeAuth').onclick=()=>$('#authModal').classList.remove('open');$('#logoutButton').onclick=()=>{localStorage.removeItem('thunarCurrentUser');updateUser();showToast('Logged out')};
['searchInput','categoryFilter','sortSelect'].forEach(id=>$('#'+id).addEventListener('input',renderProducts));$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('thunarTheme',document.body.classList.contains('dark')?'dark':'light')};$('#cartButton').onclick=()=>$('#cartPanel').classList.add('open');$('#closeCart').onclick=()=>$('#cartPanel').classList.remove('open');$('#menuToggle').onclick=()=>$('#navLinks').classList.toggle('open');$('#contactForm').onsubmit=e=>{e.preventDefault();e.target.reset();showToast('Message sent! We will contact you soon.')};
let slideIndex=0;function moveSlide(dir){const slides=document.querySelectorAll('.slide');if(!slides.length)return;slideIndex=(slideIndex+dir+slides.length)%slides.length;slideTrack.scrollTo({left:slideTrack.clientWidth*slideIndex,behavior:'smooth'})}$('#prevSlide').onclick=()=>moveSlide(-1);$('#nextSlide').onclick=()=>moveSlide(1);setInterval(()=>moveSlide(1),5000);
window.addEventListener('scroll',()=>$('#backTop').classList.toggle('show',scrollY>500));$('#backTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.16}).observe(document.body.querySelector('.hero'));document.querySelectorAll('.section-fade').forEach(el=>new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12}).observe(el));
if(localStorage.getItem('thunarTheme')==='dark')document.body.classList.add('dark');window.addEventListener('load',()=>setTimeout(()=>$('#loader').classList.add('hidden'),450));setup();
